version: '3.3'
services:
  mysql:
    build:
      context: localenvs/mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_log:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=tagnote
    - MYSQL_PASSWORD=tagnote

  redis:
    build:
      context: localenvs/redis
    volumes:
      - ./localenvs/volumes/redis/data:/var/log/redis/redis-server.log
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  mysql_log:
