spring:
  config.activate.on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config.activate.on-profile: dev
  data:
    redis:
      host: ENC(5J5edEOeF+l9qhcH9dSp3kQpEdKFtzULP5/jdgH9NEqFSe6wrbyGyHecNS/LEbxAd9RKnOJVuF0NS5v4EAnee18a/5J/MnMm)
      port: 6379