spring:
  config.activate.on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
      password: ENC(SuYUeNmx8lThaeGum7SuCl45EFRB1fyDSWw4b/cUJrE=)
---
spring:
  config.activate.on-profile: dev
  data:
    redis:
      host: ENC(vnwVK/YduADW8/m+P5bbByaIUnaPuF1ke8dD8+v84NGuRG8WTbYgEDR7JULBUlugZjXtavs1eqbZlqaEyMFu3w==)
      port: 6379
      password: ENC(zOArmr7ZqbbnBifbW6SDft0o5M+ukwY5DEWDsz03xms=)