spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/tagStory?tinyInt1isBit=false
    username: tagStory
    password: tagStory
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  config.activate.on-profile: dev
  datasource:
    url: ENC(vA79oAQ1bhq78dNyhLDWivMI86VyNKIoaGysY9IrwwSo4FUupW1JnO0YAhx2ymw+V5WJi6X1KWeC9ikbBIQhz/Wzf3TcL/6QVG9cwsJVDMDgAFpHf4cOFz8spxvbGkiCqvqUg8dc1WeBOfBPstS9FHlObwPJ5EPX)
    username: ENC(VBQnyibt9leD3hd3eo6sFA==)
    password: ENC(Z8i6MHwEh13BjDQw8WuPCgvMEAyKgM5q)
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  config.activate.on-profile: prod
  datasource:
    url: ENC(av9N7xL+qAVAY25Ae0EHrSX1n1Ao0E3McsOXp2LVlUPSLLWbwNU+5iAI1O2JxtQWoxphS7N6aIyCWjuxr8NylypoDk2Q/DKBbH6wxnrshqK/F11dZ282NTAD+/cQH9No)
    username: ENC(BHNjBGuccyPSEYFf+diLH0yn+lDn+tqr)
    password: ENC(Zz0ZJK6NA6idWRKytyIroowmo6uyRJTU)
    driver-class-name: com.mysql.cj.jdbc.Driver
