spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/tagStory?tinyInt1isBit=false
    username: tagStory
    password: tagStory
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  config.activate.on-profile: dev
  datasource:
    url: ENC(j5B7tw1hYGpuceIiVNTUx/Uj0G5Jv1q4FuGclqbuU/sDRw00eIgIEs6GVhcHBGjfm7JhprZ/3Wto1wpjVHex/nRwsLtUWCqdJ7+k9Gomp8XlC2cegEXHBQ==)
    username: ENC(S1jQxMUg+K90cobJ9ELzng==)
    password: ENC(/fMQpBA/mzEa1TdXjGVbMh7Gv5AUhhcz)
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  config.activate.on-profile: prod
  datasource:
    url: ENC(av9N7xL+qAVAY25Ae0EHrSX1n1Ao0E3McsOXp2LVlUPSLLWbwNU+5iAI1O2JxtQWoxphS7N6aIyCWjuxr8NylypoDk2Q/DKBbH6wxnrshqK/F11dZ282NTAD+/cQH9No)
    username: ENC(BHNjBGuccyPSEYFf+diLH0yn+lDn+tqr)
    password: ENC(Zz0ZJK6NA6idWRKytyIroowmo6uyRJTU)
    driver-class-name: com.mysql.cj.jdbc.Driver
