spring:
  config.activate.on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config.activate.on-profile: dev
  data:
    redis:
      host: ENC(Q4yxOqn+VrtO0Lf0uDkTmuWOdjU8KEl4ApTkkDH+ih0RoZKvHRgwAvnG4AOyVdo/I5H3c4R08aPJR6IFIbl0sLCo4D09yGMyveHJP2CaXQWnKb+pGhHTzQ==)
      port: 6379